settings:
  
drops:
  low:
    3:
      chance: 75
    4:
      chance: 75
    5:
      chance: 75
    12:
      chance: 75
    13:
      chance: 75
    17:
      chance: 75
    "17:1":
      chance: 100
    "17:2":
      chance: 100
    "17:3":
      chance: 100
    
    
  high:
    264:
      chance: 20
