#format:
# item:
  # material: iron
  # durability:
  # ingot_cost:
  # return_nuggets: false ##NOT IMPLEMENTED##

#Tools/weapons
iron_shovel:
  material: IRON_INGOT
  durability: 250
  ingot_cost: 1
  return_nuggets: false
iron_pickaxe:
  material: IRON_INGOT
  durability: 250
  ingot_cost: 3
  return_nuggets: false
iron_axe:
  material: IRON_INGOT
  durability: 250
  ingot_cost: 3
  return_nuggets: false
iron_sword:
  material: IRON_INGOT
  durability: 250
  ingot_cost: 2
  return_nuggets: false
iron_hoe:
  material: IRON_INGOT
  durability: 250
  ingot_cost: 2
  return_nuggets: false
golden_shovel:
  material: GOLD_INGOT
  durability: 32
  ingot_cost: 1
  return_nuggets: false
golden_pickaxe:
  material: GOLD_INGOT
  durability: 32
  ingot_cost: 3
  return_nuggets: false
golden_axe:
  material: GOLD_INGOT
  durability: 32
  ingot_cost: 3
  return_nuggets: false
golden_sword:
  material: GOLD_INGOT
  durability: 32
  ingot_cost: 2
  return_nuggets: false
golden_hoe:
  material: GOLD_INGOT
  durability: 32
  ingot_cost: 2
  return_nuggets: false
diamond_shovel:
  material: DIAMOND
  durability: 1561
  ingot_cost: 1
  return_nuggets: false
diamond_pickaxe:
  material: DIAMOND
  durability: 1561
  ingot_cost: 3
  return_nuggets: false
diamond_axe:
  material: DIAMOND
  durability: 1561
  ingot_cost: 3
  return_nuggets: false
diamond_sword:
  material: DIAMOND
  durability: 1561
  ingot_cost: 2
  return_nuggets: false
diamond_hoe:
  material: DIAMOND
  durability: 1561
  ingot_cost: 2
  return_nuggets: false

#armor
leather_helmet:
  material: LEATHER
  durability: 55
  ingot_cost: 5
  return_nuggets: false
leather_chestplate:
  material: LEATHER
  durability: 80
  ingot_cost: 8
  return_nuggets: false
leather_leggings:
  material: LEATHER
  durability: 75
  ingot_cost: 7
  return_nuggets: false
leather_boots:
  material: LEATHER
  durability: 65
  ingot_cost: 4
  return_nuggets: false
chainmail_helmet:
  material: IRON_INGOT
  durability: 165
  ingot_cost: 5
  return_nuggets: false
chainmail_chestplate:
  material: IRON_INGOT
  durability: 240
  ingot_cost: 8
  return_nuggets: false
chainmail_leggings:
  material: IRON_INGOT
  durability: 225
  ingot_cost: 7
  return_nuggets: false
chainmail_boots:
  material: IRON_INGOT
  durability: 195
  ingot_cost: 4
  return_nuggets: false
iron_helmet:
  material: IRON_INGOT
  durability: 165
  ingot_cost: 5
  return_nuggets: false
iron_chestplate:
  material: IRON_INGOT
  durability: 240
  ingot_cost: 8
  return_nuggets: false
iron_leggings:
  material: IRON_INGOT
  durability: 225
  ingot_cost: 7
  return_nuggets: false
iron_boots:
  material: IRON_INGOT
  durability: 195
  ingot_cost: 4
  return_nuggets: false
golden_helmet:
  material: GOLD_INGOT
  durability: 77
  ingot_cost: 5
  return_nuggets: false
golden_chestplate:
  material: GOLD_INGOT
  durability: 112
  ingot_cost: 8
  return_nuggets: false
golden_leggings:
  material: GOLD_INGOT
  durability: 105
  ingot_cost: 7
  return_nuggets: false
golden_boots:
  material: GOLD_INGOT
  durability: 91
  ingot_cost: 4
  return_nuggets: false
diamond_helmet:
  material: DIAMOND
  durability: 363
  ingot_cost: 5
  return_nuggets: false
diamond_chestplate:
  material: DIAMOND
  durability: 528
  ingot_cost: 8
  return_nuggets: false
diamond_leggings:
  material: DIAMOND
  durability: 495
  ingot_cost: 7
  return_nuggets: false
diamond_boots:
  material: DIAMOND
  durability: 429
  ingot_cost: 4
  return_nuggets: false
